#!/usr/bin/env python

# shows mp3 info using python mutagen lib
# mp3info "%a %l %t" file_name
# %a for an artist, %l for an album, %t for a title

import sys
sys.tracebacklimit=0
import re
from mutagen.id3 import ID3

def show_usage():
  print 'Usage: ' + sys.argv[0] + ' "%a %l %t" file_name.mp3'

def main(argv):
  try:
    if len(sys.argv) < 3:
      show_usage() 
      sys.exit(2)
    t=sys.argv[1]
    a=ID3(sys.argv[2])
    if not t or not a:
      sys.exit(1)
    t=re.sub('%a',a['TPE1'].text[0],t)
    t=re.sub('%l',a['TALB'].text[0],t)
    t=re.sub('%t',a['TIT2'].text[0],t)
    sys.stdout.write(t+'\n')
  except:
    sys.exit(0)

if __name__ == "__main__":
  main(sys.argv)

