BOLD='\e[1m'              # bold
DIM='\e[2m'               # dim
UNDERLINE='\e[4m'         # underlined
INVERT='\e[7m'            # inverted

BLACK='\e[0;30m'          # ${black}
RED='\e[0;31m'            # ${red}
GREEN='\e[0;32m'          # ${green}
YELLOW='\e[0;33m'         # ${yellow}
BLUE='\e[0;34m'           # ${blue}
MAGENTA='\e[0;35m'        # ${purple}
CYAN='\e[0;36m'           # ${cyan}
LIGHTGRAY='\e[0;37m'      # ${lightgray}
DARKGRAY='\e[1;30m'       # ${darkgray}
LIGHTRED='\e[1;31m'       # ${lightred}
LIGHTGREEN='\e[1;32m'     # ${lightgreen}
LIGHTYELLOW='\e[1;33m'    # ${yellow}
LIGHTBLUE='\e[1;34m'      # ${lightblue}
LIGHTMAGENTA='\e[1;35m'   # ${lightpurple}
LIGHTCYAN='\e[1;36m'      # ${lightcyan}
WHITE='\e[1;37m'          # ${white}

BLACKBG='\e[40m'          # ${black}
REDBG='\e[41m'            # ${red}
GREENBG='\e[42m'          # ${green}
YELLOWBG='\e[43m'         # ${yellow}
BLUEBG='\e[44m'           # ${blue}
MAGENTABG='\e[45m'        # ${purple}
CYANBG='\e[46m'           # ${cyan}
LIGHTGRAYBG='\e[47m'      # ${lightgray}
DARKGRAYBG='\e[100m'      # ${darkgray}
LIGHTREDBG='\e[101m'      # ${lightblue}
LIGHTGREENBG='\e[102m'    # ${lightgreen}
LIGHTYELLOWBG='\e[103m'   # ${yellow}
LIGHTBLUEBG='\e[104m'     # ${lightblue}
LIGHTMAGENTABG='\e[105m'  # ${lightpurple}
LIGHTCYANBG='\e[106m'     # ${lightcyan}
WHITEBG='\e[107m'         # ${white}

NC='\e[0m'                # ${nc} (no color - resets previous color selection)
